Death animation
bbeck13/RhythmRunner pull request #145
Opened 2017-03-08 00:04 UTC by josepharhar

2017-03-09 20:13 UTC, bbeck13 commented
Fixed some of your logic 
CR 👍 QA 👍

2017-03-09 20:16 UTC, bbeck13 submitted a review, later dismissed

2017-03-09 20:16 UTC, bbeck13 commented on src/game_state/GameState.cpp
> +        music->stop();
The music should stop when the player fails

2017-03-09 20:16 UTC, bbeck13 commented on src/game_updater/GameUpdater.cpp
> +      (music->getStatus() != sf::SoundSource::Status::Playing)) {
A bit of paranoia here

2017-03-09 23:47 UTC, alexottoboni commented
You die, if you hit the ground too fast. 👎

2017-03-10 20:48 UTC, josepharhar commented
@alexottoboni I believe that I fixed the death on hitting the ground too fast.
@bbeck13 @Matthew-Stewart are you guys still having any sfml issues on this branch?

2017-03-10 21:13 UTC, Matthew-Stewart commented
Not sure if I had sfml issues before, but everything seems to be working

2017-03-11 19:40 UTC, bbeck13 requested changes
refactors look ok overall I'm able to follow the style and the changes you made, game runs fine 👌

2017-03-11 19:40 UTC, bbeck13 commented on src/game_updater/PlayerUpdater.cpp
> +    player->SetRotationAngle(std::atan(player->GetYVelocity() * 4));
It looks a little jaring when the player lands from a long fall can you try this
```cpp
float vel = std::atan(player->GetYVelocity()*4;
if (vel < 0)
  player->SetRotationAngle(std::min(0.872665, vel);
else
    player->SetRotationAngle(std::max(-0.872665, vel);
```
0.872665 is about 50 degrees y The idea here is that the player should never go past +-50 degrees.

2017-03-11 19:45 UTC, josepharhar commented on src/game_updater/PlayerUpdater.cpp
> +    player->SetRotationAngle(std::atan(player->GetYVelocity() * 4));
Done, not sure if i can tell the difference though

2017-03-11 19:53 UTC, bbeck13 requested changes

2017-03-11 19:53 UTC, bbeck13 commented on src/game_updater/PlayerUpdater.cpp
> +#define MAX_AERIAL_ROTATION_ANGLE 0.872665f
Change this to .67 it looks a lot better

2017-03-11 20:13 UTC, josepharhar commented on src/game_updater/PlayerUpdater.cpp
> +#define MAX_AERIAL_ROTATION_ANGLE 0.872665f
Done, I can tell the difference now :ok_hand:

2017-03-11 20:37 UTC, bbeck13 approved these changes

2017-03-11 20:37 UTC, bbeck13 commented
CR 👍 QA 💺

2017-03-11 20:41 UTC, merged